const STATUSES = {
    DELIVERED:"DELIVERED",
    DELIVERED_TO_SENDER:"DELIVERED_TO_SENDER",
    OUT_FOR_DELIVERY:"OUT_FOR_DELIVERY",
    PACKAGE_RECEIVED:"PACKAGE_RECEIVED",
    TICKET_CREATED:"TICKET_CREATED",
  };

  export default STATUSES;